"""Contratos das plataformas usados pela sincronização."""
from typing import Protocol


class StudentSource(Protocol):
    def students(self) -> list[dict]: ...
    def teachers(self) -> list[dict]: ...
    def teaching_catalog(self) -> list[dict]: ...


class UserDestination(Protocol):
    def find(self, field: str, value: str) -> list[dict]: ...
    def create(self, user: dict) -> int: ...
    def check_teaching_setup(self) -> None: ...
    def find_course(self, field: str, value: str) -> list[dict]: ...
    def create_course(self, course: dict) -> int: ...
    def course_teachers(self, course_id: int) -> set[int]: ...
    def enrol_teacher(self, user_id: int, course_id: int) -> None: ...
    def check_student_setup(self) -> None: ...
    def course_students(self, course_id: int) -> set[int]: ...
    def enrol_students(self, user_ids: list[int], course_id: int) -> None: ...
